# Generated by Django 3.2.4 on 2021-07-10 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_financiera', '0003_retiro'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transferencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cuenta_origen', models.CharField(max_length=40)),
                ('cuenta_destino', models.CharField(max_length=40)),
                ('fecha_transferencia', models.DateTimeField(auto_now_add=True)),
                ('monto_depositar', models.DecimalField(decimal_places=2, max_digits=10)),
                ('descripcion_transferencia', models.TextField()),
            ],
        ),
    ]
