# Generated by Django 3.2.4 on 2021-07-10 23:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app_financiera', '0005_transacciones'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transacciones',
            old_name='Deposito',
            new_name='deposito',
        ),
        migrations.RenameField(
            model_name='transacciones',
            old_name='Retiro',
            new_name='retiro',
        ),
        migrations.RenameField(
            model_name='transacciones',
            old_name='Transferencia',
            new_name='transferencia',
        ),
        migrations.RemoveField(
            model_name='deposito',
            name='monto',
        ),
        migrations.AddField(
            model_name='cliente',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
